config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users
    resources :groups do
      resources :entities
    end  

  authenticated :user do
    root :to => 'groups#index', as: :authenticated_root
  end

  root 'users#index'
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    can :read, User

    return unless user.present?

    can :manage, Group, user_id: user.id
    can :manage, Purchase, user_id: user.id
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/entity.rb
class Entity < ApplicationRecord
  has_and_belongs_to_many :groups
  belongs_to :user

  validates :name, presence: true
  validates :amount, presence: true
  validates :amount, numericality: { greater_than_or_equal_to: 0 }
end

app/models/group.rb
class Group < ApplicationRecord
  has_and_belongs_to_many :entities, dependent: :destroy
  belongs_to :user

  validates :name, presence: true
  validates :icon, presence: true

  def expenses_group_sum
    entities.sum(:amount)
  end
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :group, dependent: :destroy
  has_many :entity, dependent: :destroy

  validates_presence_of :name

  def expenses_sum_user
    entity.sum(:amount)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :update_allowed_parameters, if: :devise_controller?

  # rescue_from CanCan::AccessDenied do |exception|
  #   redirect_to root_url, alert: exception.message
  # end

  protected

  def update_allowed_parameters
    devise_parameter_sanitizer.permit(:sign_up) do |u|
      u.permit(:name, :email, :password, :password_confirmation)
    end

    devise_parameter_sanitizer.permit(:account_update) do |u|
      u.permit(:name, :email, :password, :current_password)
    end
  end
end

app/controllers/entities_controller.rb
class EntitiesController < ApplicationController
  before_action :set_entity, only: %i[show edit update destroy]
  before_action :set_group, only: %i[new edit create index]

  def index
    @entities = @group.entities.order(created_at: :desc)
    @expenses_group = @group.entities.sum(:amount)
  end

  def show; end

  def new
    @entity = Entity.new
  end

  def edit; end

  def create
    @entity = @group.entities.create(entity_params)

    respond_to do |format|
      if @entity.save
        format.html { redirect_to group_entities_path, notice: 'Transaction created.' }
        format.json { render :show, status: :created, location: @entity }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @entity.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @entity.update(entity_params)
        format.html { redirect_to group_entities_path, notice: 'Entity was successfully updated.' }
        format.json { render :show, status: :ok, location: @entity }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @entity.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @entity.destroy
    respond_to do |format|
      format.html { redirect_to group_entities_path, notice: 'Entity was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  def set_entity
    @entity = Entity.find(params[:id])
  end

  def set_group
    @group = Group.find(params[:group_id])
  end

  def entity_params
    params.require(:entity).permit(:name, :amount).merge(user_id: current_user.id)
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :set_group, only: %i[show edit update destroy]

  def index
    @groups = Group.where(user_id: current_user.id)
    @user = current_user
    @expenses = @user.expenses_sum_user
  end

  def show; end

  def new
    @group = Group.new
    @icons = %w[House Food Investment]
  end

  def edit; end

  def create
    @group = Group.new(group_params)
    @group.user_id = current_user.id
    respond_to do |format|
      if @group.save
        format.html { redirect_to groups_path, notice: 'Category created.' }
        format.json { render :show, status: :created, location: @group }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @group.update(group_params)
        format.html { redirect_to @group, notice: 'Group was successfully updated.' }
        format.json { render :show, status: :ok, location: @group }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @group.destroy
    respond_to do |format|
      format.html { redirect_to groups_url, notice: 'Group was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  def set_group
    @group = Group.find(params[:id])
  end

  def group_params
    params.require(:group).permit(:name, :icon, :user_id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[show edit update destroy]
  def index; end

  # GET /users/1 or /users/1.json
  def show; end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit; end

  # POST /users or /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1 or /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1 or /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_user
    @user = User.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def user_params
    params.require(:user).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/entities_helper.rb
module EntitiesHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
  def list_icons
    [
      ['Travel', 'travel.png'],
      ['Car', 'car.png'],
      ['Games', 'console.png'],
      ['Books', 'books.png'],
      ['Fitness', 'dumbbell.png'],
      ['Entertainment', 'entertainment.png'],
      ['Food', 'food.png'],
      ['Home', 'home.png']
    ]
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/entities/_form.html.erb
<%= form_with(model: [@group, @entity]) do |form| %>

  <% if entity.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(entity.errors.count, "error") %> prohibited this entity from being saved:</h2>
      <ul>
        <% entity.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">    
    <%= form.text_field :name, class:'form_fields', placeholder: 'Name' %>
  </div>

  <div class="field">    
    <%= form.number_field :amount, class:'form_fields', placeholder: 'Amount' %>
  </div>

  <div class="actions">
    <%= form.submit 'Create Transactions'%>
  </div>
<% end %>

app/views/entities/edit.html.erb
<h1>Editing Entity</h1>

<%= render 'form', entity: @entity %>

<%= link_to 'Show', @entity %> |
<%= link_to 'Back', entities_path %>

app/views/entities/index.html.erb
<div class="nav_container">
<%= link_to groups_path, class: "icons" do %>
  <i class="fas fa-arrow-left fa-2x"></i>
<% end %>
<h1>Transactions</h1>
<%= link_to destroy_user_session_path, method: :delete, class: "icons" do %>
  <i class="fas fa-sign-out-alt fa-2x"></i>
<% end %>
</div>
<div class="total_ctn">
<p class="total_expended">Total group expenses: </p><p class='value_sum'>$<%= @expenses_group %></p>
</div>
<% if user_signed_in?%>  
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p> 
<%end%>
 <ul>  
    <% @entities.each do |entity| %>
      <li class="category_li">  
        <div class="entity_content">
        <h3><%= entity.name %></h3>
        <p><%= entity.created_at.strftime("%d %b %Y")%></p>
        </div>
        <p class="entity_content value_sum">$<%= entity.amount %></p>    
      </li>      
    <% end %>
  </ul>
<br>
<div class="category_btn_cnt">
<%= link_to 'New Transaction', new_group_entity_path, class:"category_btn" %>
</div>

app/views/entities/new.html.erb
<div class="nav_container">
<%= link_to group_entities_path, class: "icons" do %>
<i class="fas fa-arrow-left fa-2x"></i>
<% end %>
<h1>New Transactions</h1>
<%= link_to destroy_user_session_path, method: :delete, class: "icons" do %>
  <i class="fas fa-sign-out-alt fa-2x"></i>
<% end %>
</div>

<%= render 'form', entity: @entity %>

<%= link_to 'Back', group_entities_path %>

app/views/entities/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @entity.name %>
</p>

<p>
  <strong>Amount:</strong>
  <%= @entity.amount %>
</p>

<p>
  <strong>User:</strong>
  <%= @entity.user_id %>
</p>

<%= link_to 'Edit', edit_entity_path(@entity) %> |
<%= link_to 'Back', entities_path %>

app/views/groups/_form.html.erb
<%= form_with(model: group) do |form| %>
  <% if group.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(group.errors.count, "error") %> prohibited this group from being saved:</h2>
      <ul>
        <% group.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">    
    <%= form.text_field :name, class:'form_fields', placeholder: 'Name' %>
  </div>

  <div class="field">
  <%= form.select(:icon, options_for_select(list_icons), {} , {class:'form_fields'}) %>     
  </div>
 
  <div class="actions">
    <%= form.submit 'Create Category'%>
  </div>

<% end %>

app/views/groups/edit.html.erb
<h1>Editing Group</h1>

<%= render 'form', group: @group %>

<%= link_to 'Show', @group %> |
<%= link_to 'Back', groups_path %>

app/views/groups/index.html.erb
<div class="nav_container">
<div class="search_cnt">
<i class="fas fa-search fa-2x"></i>
</div>
<h1>Category</h1>
<%= link_to destroy_user_session_path, method: :delete, class: "icons" do %>
  <i class="fas fa-sign-out-alt fa-2x"></i>
<% end %>
</div>
<div class="total_ctn">
<p class="total_expended">Total expended: </p><p class='value_sum'>$<%= @expenses %></p>
</div>
<% if user_signed_in?%>  
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p> 
    <%end%>
<ul>
<% @groups.each do |group| %>
<%= link_to group_entities_path(group.id) do %>
  <li class="category_li">
  <div class="category_content">
    <%= image_tag "#{group.icon}", alt: 'icon', class: 'category_image'%>
    <div>
    <h3><%= group.name %></h3>
    <p><%= group.created_at.strftime("%d %b %Y")%></p>
    </div>
  </div>  
    <p class="entity_content value_sum">$<%= group.expenses_group_sum %></p>   
  </li>
  <% end %>
<% end %>
</ul>
<div class="category_btn_cnt">
<%= link_to 'New Category', new_group_path, class:"category_btn" %>
</div>

app/views/groups/new.html.erb
<div class="nav_container">
<%= link_to groups_path, class: "icons" do %>
  <i class="fas fa-arrow-left fa-2x"></i>
<% end %>
<h1>New Category</h1>
<%= link_to destroy_user_session_path, method: :delete, class: "icons" do %>
  <i class="fas fa-sign-out-alt fa-2x"></i>
<% end %>
</div>

<%= render 'form', group: @group %>

app/views/groups/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @group.name %>
</p>

<p>
  <strong>Icon:</strong>
  <%= @group.icon %>
</p>

<p>
  <strong>User:</strong>
  <%= @group.user_id %>
</p>

<%= link_to 'Edit', edit_group_path(@group) %> |
<%= link_to 'Back', groups_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RecipeRorcapstone</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css2?family=Caveat:wght@600&family=Outfit:wght@100;600&display=swap" rel="stylesheet">
    <script src="https://kit.fontawesome.com/3410ed71d0.js" crossorigin="anonymous"></script>
  </head>

  <body>  
    <%= yield %>
    </body>
</html>

app/views/users/_form.html.erb
<%= form_with(model: user) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/users/_nav.html.erb
<header class="container">
<div class="nav_container">
    <h1>Recipes App</h1>
    <nav>
        <ul class="options_container">
            <% unless user_signed_in? %>
                <li>
                    <%= link_to "Log in", new_user_session_path %>
                </li>
            <% end %>
            <% if user_signed_in? %>
            <li>
                <%= link_to "Groups", groups_path %>
            </li>
            <li>
                <%= link_to "Entities", entities_path %>
            </li>           
                <li>
                    <%= link_to "Log out", destroy_user_session_path, method: :delete %>
                </li>
                <li>
                    <button class="btn btn-outline-success">Hello <%= current_user.name %></button>
                </li>
                <% end %>
        </ul>
    </nav>
    </div>
</header>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<div class="root_title_cnt">
<h1 class="root_title">Budgeteer</h1>
</div>
<p id="notice"><%= notice %></p>
<div class="root_btn_cnt">
<%= button_to "LOG IN", new_user_session_path, class: 'login_btn' %>  
<%= link_to "SIGN UP", new_user_registration_path, class: 'signup_btn' %>
</div>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>